### PR TITLE
Increase memory (and CPU) allocation

### PR DESCRIPTION
**Pull request by jacobwinch**
This should help us with the timeout issues/alarms whilst we are working on a longer term queuing strategy.

cc @johnduffell @paulbrown1982

### CODE REVIEW

**Comment by johnduffell** [comment]
thanks!  is it worth understanding the cost change?
probably not as it could only be triple at the most, but firstly it should be quicker and secondly less should "fail" so we won't have as many retries. 
but I'll admit I don't know how much auto cancel/PF lambda costs us. less than an auto scaling group/elb?
👍 🚀

**Comment by jacobwinch** [comment]
I think the trade off between speed of execution vs memory used would be an interesting one if we were using lambdas at scale, but based on what I can work out from the billing console, our current costs for lambda usage are so low that even if we tripled the cost it would be negligible...

**Comment by jacobwinch** [comment]
There's a noticeable drop in the max execution times for these lambdas:

image

**Comment by johnduffell** [comment]
what does each line mean and what is the scale on the vertical?

**Pull request merged**
